---
- name: create deploy folder
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: Copy artifact
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    force: no
    
- name: Copy node_modules
  become: true
  copy:
    src: node_modules.tar.gz
    dest: /home/ubuntu/backend/node_modules.tar.gz
    force: no

- name: Unpack artifact
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    tar -vxf node_modules.tar.gz

- name: "run server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/backend/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

